//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdaje
    {
        public int ReceptOznaka_R { get; set; }
        public int UspostavljaPregledBroj_P { get; set; }
        public int UspostavljaDijagnozaOznaka_D { get; set; }
    
        public virtual Recept Recept { get; set; }
        public virtual Uspostavlja Uspostavlja { get; set; }
    }
}
