//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public int Jmbg { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int BolnicaOznaka_B { get; set; }
        public string Radni_staz { get; set; }
        public int MestoP_Broj { get; set; }
    
        public virtual Bolnica Bolnica { get; set; }
        public virtual Mesto Mesto { get; set; }
    }
}
