//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poseduje
    {
        public int ZdravstveniKartonBroj_K { get; set; }
        public int TerapijaBroj_T { get; set; }
    
        public virtual ZdravstveniKarton ZdravstveniKarton { get; set; }
        public virtual Terapija Terapija { get; set; }
    }
}
