//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uspostavlja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uspostavlja()
        {
            this.Izdajes = new HashSet<Izdaje>();
        }
    
        public int PregledBroj_P { get; set; }
        public int LecenjeTerapijaBroj_T { get; set; }
        public int LecenjeDijagnozaOznaka_D { get; set; }
        public int DijagnozaOznaka_D { get; set; }
    
        public virtual Pregled Pregled { get; set; }
        public virtual Lecenje Lecenje { get; set; }
        public virtual Dijagnoza Dijagnoza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izdaje> Izdajes { get; set; }
    }
}
